# Configuration for the steer_drive_controller.
steer_drive_controller:
  type: "steer_drive_controller/SteerDriveController"
  publish_rate: 50.0

  rear_wheel  : 'rear_wheel_joint'
  front_steer : 'front_steer_joint'

  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  
  wheel_separation_h : 0.4
  wheel_radius : 0.1
  wheel_separation_h_multiplier: 1.0
  