<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bicycle">
    <!-- Xacro includes -->
    <xacro:include filename="$(find acky_bot_description)/urdf/materials.xacro"/>
    <xacro:include filename="$(find acky_bot_description)/urdf/inertials.xacro"/>

    <xacro:property name="robot_namespace" value="/acky_bot"/>

    <!-- Gazebo plugins -->
    <gazebo>
        <!-- Load ros_control plugin -->
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>${robot_namespace}</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <legacyModeNS>false</legacyModeNS>
        </plugin>

        <!-- Load gazebo_ros plugin. Publish passive (non-actuated) joints from Gazebo -->
        <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
            <robotNamespace>${robot_namespace}</robotNamespace>
            <jointName>
                front_wheel_joint
            </jointName>
            <updateRate>50</updateRate>
            <alwaysOn>true</alwaysOn>
        </plugin>

    </gazebo>

    <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="degrees_180" value="3.14159265"/>

    <!-- Basic Geometry of Body -->
    <xacro:property name="body_length" value="2.0" />
    <xacro:property name="body_width" value="0.7" />
    <xacro:property name="body_height" value="1.0" />
    <xacro:property name="body_mass" value="10"/>

    <!-- Front Steer (Motor) Properties -->
    <xacro:property name="front_steer_width" value="0.4" />
    <xacro:property name="front_steer_diameter" value="0.3" />
    <xacro:property name="front_steer_mass" value="2"/>

    <!-- Front Wheel Properties -->
    <xacro:property name="front_wheel_width" value="0.4" />
    <xacro:property name="front_wheel_diameter" value="0.6" />
    <xacro:property name="front_wheel_mass" value="5"/>

    <!-- Rear Wheel Properties -->
    <xacro:property name="rear_wheel_width" value="0.4" />
    <xacro:property name="rear_wheel_diameter" value="0.6" />
    <xacro:property name="rear_wheel_mass" value="5"/>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:solid_cuboid_inertial 
            rpy="0 0 0" xyz="0 0 0"
            mass="${body_mass}"
            x="${body_length}" y="${body_width}" z="${body_height}" />
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <link name="front_steer">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${front_steer_diameter/2}" length="${front_steer_width}"/>
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${front_steer_diameter/2}" length="${front_steer_width}"/>
            </geometry>
        </collision>
        <xacro:solid_cylinder_inertial
            rpy="${degrees_90} 0 0" xyz="0 0 0"
            mass="${front_steer_mass}"
            radius="${front_steer_diameter/2}" length="${front_steer_width}" />
    </link>

    <gazebo reference="front_steer">
        <material>Gazebo/Green</material>
    </gazebo>

    <joint name="front_steer_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_steer"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.7 0 0" rpy="0 0 0"/>
        <limit lower="-0.50" upper="0.50" effort="1000" velocity="3" />
    </joint>

    <transmission name="front_steer_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_steer_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="front_steer_joint_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <link name="front_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
            <geometry>
                <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
            <geometry>
                <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
            </geometry>
        </collision>
        <xacro:solid_cylinder_inertial
            rpy="${degrees_90} 0 0" xyz="0 0 0"
            mass="${front_wheel_mass}"
            radius="${front_wheel_diameter/2}" length="${front_wheel_width}" />
    </link>

    <gazebo reference="front_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="front_wheel_joint" type="continuous">
        <parent link="front_steer"/>
        <child link="front_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 ${-body_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="rear_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
            <geometry>
                <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
            <geometry>
                <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
            </geometry>
        </collision>
        <xacro:solid_cylinder_inertial
            rpy="${degrees_90} 0 0" xyz="0 0 0"
            mass="${rear_wheel_mass}"
            radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}" />
    </link>

    <gazebo reference="rear_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="-0.70 0 ${-body_height/2}" rpy="0 0 0"/>
    </joint>

    <transmission name="rear_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="rear_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="rear_wheel_joint_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot>